### ISSUE TITLE
Invalid type for Profile

### ISSUE THREAD

**Issue by HryMar** [bvirxx/bLUe_PYSIDE2#2]
Got this error, while running bLUe.py:

Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
libpng warning: iCCP: known incorrect sRGB profile
2
Profile: None
Unexpected error: <class 'PIL.ImageCms.PyCMSError'>
Traceback (most recent call last):
  File "/bLUe_PYSIDE2-master/env/lib/python3.5/site-packages/PIL/ImageCms.py", line 726, in getProfileInfo
    profile = ImageCmsProfile(profile)
  File "/bLUe_PYSIDE2-master/env/lib/python3.5/site-packages/PIL/ImageCms.py", line 168, in __init__
    raise TypeError("Invalid type for Profile")
TypeError: Invalid type for Profile

Tested on Macos, Ubuntu and Windows.

Should I change some configuration?

**Comment by bvirxx** [comment]
Le sam. 6 avr. 2019 à 12:13, Markiiian Hryhorchuk <notifications@github.com>
a écrit :

> *Got this error, while running bLUe.py:*
>
> Qt WebEngine seems to be initialized from a plugin. Please set
> Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before
> constructing QGuiApplication.
>
    Qt WebEngine is not needed by bLUe.
    Please try the last commit for the file QtGui1.py : I added a line to set the
    flag AA_ShareOpenGLContexts.

> libpng warning: iCCP: known incorrect sRGB profile*
>
      libpng may reject profiles embedded by some applications in png files.  This is a known issue.
      See
https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile
      It is safe to ignore the warning (however see 2 below)

> 2  Profile: None Unexpected error: <class 'PIL.ImageCms.PyCMSError'>
> Traceback (most recent call last): File
> "/bLUe_PYSIDE2-master/env/lib/python3.5/site-packages/PIL/ImageCms.py",
> line 726, in getProfileInfo profile = ImageCmsProfile(profile) File
> "/bLUe_PYSIDE2-master/env/lib/python3.5/site-packages/PIL/ImageCms.py",
> line 168, in init raise TypeError("Invalid type for Profile") TypeError:
> Invalid type for Profile 
>
     Set SRGB_PROFILE_PATH in the configuration file settings.py. It must be a valid path to a sRGB profile.
     When a valid color profile cannot be found in an image,  bLUe try to
    load  a corresponding profile from disk. Currently, only a sRGB profile is loaded in this way 
    from SRGB_PROFILE_PATH.

**Comment by HryMar** [comment]
Thanks for your response!

Actually, error occurs before using SRGB_PROFILE_PATH:

61-69 colorManagement.py
```
        try:
            # get monitor profile as CmsProfile object.
            if qscreen is not None:
                cls.monitorProfile = cls.getMonitorProfile(qscreen=qscreen)
                # get profile info, a PyCmsError exception is raised if monitorProfile is invalid
                cls.monitorProfileInfo = getProfileInfo(cls.monitorProfile)
            # get working profile as CmsProfile object
            if colorSpace == 1:
                cls.workingProfile = getOpenProfile(SRGB_PROFILE_PATH)
```

cls.monitorProfile = None, because function get_display_profile in PIL defined only for win32 system.
So, error occurs here:
cls.monitorProfileInfo = getProfileInfo(cls.monitorProfile).


That was for Macos, for Win64 I got: 

> DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="courier", pointsize=8, pixelsize=16, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("courier", lfWidth=0, lfHeight=-16) dpi=144

while running this line:
cls.monitorProfile = cls.getMonitorProfile(qscreen=qscreen).


SRGB_PROFILE_PATH path set correctly, cls.monitorProfile has not None output.

**Comment by bvirxx** [comment]
> Thanks for your response!
> 
> Actually, error occurs before using SRGB_PROFILE_PATH:
> 
> 61-69 colorManagement.py
> 
> ```
>         try:
>             # get monitor profile as CmsProfile object.
>             if qscreen is not None:
>                 cls.monitorProfile = cls.getMonitorProfile(qscreen=qscreen)
>                 # get profile info, a PyCmsError exception is raised if monitorProfile is invalid
>                 cls.monitorProfileInfo = getProfileInfo(cls.monitorProfile)
>             # get working profile as CmsProfile object
>             if colorSpace == 1:
>                 cls.workingProfile = getOpenProfile(SRGB_PROFILE_PATH)
> ```
> cls.monitorProfile = None, because function get_display_profile in PIL defined only for win32 system.
> So, error occurs here:
> cls.monitorProfileInfo = getProfileInfo(cls.monitorProfile).
>
Right! PIL getProfileInfo does not raise an exception for None profile. I added a correction in colorManagement.configure(), to turn off color management when no valid profile is found.
> 
> That was for Macos, for Win64 I got:
> 
> > DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="courier", pointsize=8, pixelsize=16, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("courier", lfWidth=0, lfHeight=-16) dpi=144
> 
> while running this line:
> cls.monitorProfile = cls.getMonitorProfile(qscreen=qscreen).
> 

This is a Qt error, likely caused by qscreen.name().  I was not able to reproduce it, but I added an explicit conversion from QString to python str for the call to createDC in getMonitorProfile.  If the problem remains, could you tell me which value is returned by qscreen.name() ? 
 
To enable improvements in multi-OS screen profile detection, I also replaced  usages of the PIL function get_display_profile() by a modified version B_get_display_profile(), which works for Win64 (at least windows 7).  However, it probably should be completed for other OS.
