### ISSUE TITLE
ARW picture crash

### ISSUE THREAD

**Issue by electro-logic** [bvirxx/bLUe_PYSIDE2#7]
Thanks for the ARW support.

Some images are working, but this one is crashing the software
[_LTZ8437.zip](https://github.com/bvirxx/bLUe_PYSIDE/files/13179512/_LTZ8437.zip)

Thank you
Cheers,
Leonardo

**Comment by bvirxx** [comment]
Your image works well for me. Could you give me more details on the crash
you observed ?

Thank you

bvirxx

**Comment by electro-logic** [comment]
Hi bvirxx,

I just opened the image and the software crashed.
I found this in the Event Viewer:

Faulting application name: bLUe.exe, version: 0.0.0.0, time stamp: 0x653a4684
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000001
Faulting process ID: 0x0x48E4
Faulting application start time: 0x0x1DA08286830923F
Faulting application path: C:\Users\*\bLUe\bLUe.exe
Faulting module path: unknown
Report ID: 3210c0e6-9277-4b95-a361-832904fb68df
Faulting package full name: 
Faulting package-relative application ID: 

I tried again after restarting the computer and everything worked fine.
